### PR TITLE
Add setCookieEnabled and tests

### PR DESCRIPTION
**Pull request by fgagne**
Add a `setCookieEnabled` option to disable the locale cookie. Also add 2 tests.

### CODE REVIEW

**Comment by tboronczyk** [comment]
I'm uncertain whether this functionality is warranted. I'd be interested in hearing about your use case and why you feel it is necessary.

**Comment by fgagne** [comment]
I mostly use the middleware with the `LocalizationMiddleware::FROM_HEADER` to parse the user locale preference and show a page corresponding to that locale.  Polluting the header / cookies is unnecessary for that use case. In fact, I feel setting the cookie should be disabled by default but to not break BC, I left it enabled by default in the proposed PR.

English is not my first language, I can change the name of the function `setCookieEnabled` or class member if you wish. Or, in fact, anything else to your liking ;)

**Comment by tboronczyk** [comment]
I see your point. But the problem then is you need to parse the header for each request. Using the cookie allows you to parse it once and reuse the result in subsequent requests and saves a little bit of processing.

**Comment by fgagne** [comment]
After the first request, the locale could be parsed with `LocalizationMiddleware::FROM_URI_PATH` or with a route group parameter. The cookie goes unused.

As for saving a bit of processing, the `Cookie` and `Accept-Language` are both request headers. The difference between parsing one or the other should be marginal.

**Comment by tboronczyk** [comment]
Indeed, but cookie parsing would probably happen regardless and there is less effort to obtain its value as opposed to splitting, sorting, matching, and selecting a locale from a list of possibilities that would be sent in `Accept-Header`.

Perhaps a better approach would be to have all of these parsing steps optional and only occur when they are defined with `setSearchOrder()`. That is, something like this:

    $middleware->setSearchOrder([
        LocalizationMiddleware::FROM_URI_PATH,
        LocalizationMiddleware::FROM_URI_PARAM,
        LocalizationMiddleware::FROM_COOKIE,
        LocalizationMiddleware::FROM_HEADER
    ]);

would search all of those aspects of the request in that order. But then something like this:

    $middleware->setSearchOrder([
        LocalizationMiddleware::FROM_URI_PATH,
        LocalizationMiddleware::FROM_URI_PARAM,
        LocalizationMiddleware::FROM_HEADER
    ]);

would only search those three. 

Thoughts?

**Comment by tboronczyk** [comment]
... we'd probably then want to change the name of the method to something like `setSearch()`

**Comment by tboronczyk** [comment]
... actually, that's how it works now (it's been a while since I've really looked at the code, sorry!) What we probably need is to not set the cookie if it's not in the search.

**Comment by tboronczyk** [comment]
Try this update: https://github.com/tboronczyk/localization-middleware/pull/9

**Pull request closed without merging**
